version: '3.8'

services:
  django:

    command: python3 manage.py runserver 0.0.0.0:8000

    build:
      context: .
      dockerfile: Dockerfile
      
    image: django
    
    volumes:
      - .:/app
    
    
    ports:
      - 8000:8000